import { team } from '../../data/content.mjs';
import { finalCta, logoStrip } from '../components.mjs';
import { breadcrumb, pageHeroArt, sectionHeading } from '../templates.mjs';

export function aboutPage() {
  return `
    <section class="page-hero page-hero--about">${pageHeroArt('about')}<div class="shell">${breadcrumb([{ name: 'Home', path: '/' }, { name: 'About', path: '/about/' }])}<div class="page-hero__grid"><div><p class="kicker">About Leadapreneur</p><h1>We built Leadapreneur to future-proof your talent.</h1></div><p class="page-hero__lede">For 20 years, we have prepared people for what comes next by asking them to build—not merely learn.</p></div></div></section>
    <section class="section founder-section" aria-labelledby="founder-title"><div class="shell founder-grid"><figure><img src="/images/ceo-jan.jpg" alt="Jan Henrik Bartscht, founder and CEO of Leadapreneur" width="1200" height="1200"></figure><div><p class="kicker">Founder & CEO</p><h2 id="founder-title">Meet Jan Henrik Bartscht.</h2><p>With roots in the UK and Germany and two decades of work across Southeast Asia, Jan is a futurist, disruptor and practitioner focused on reshaping leadership and innovation.</p><p>His core belief is exacting: people reveal their potential through useful work. Leadapreneur’s methods turn that belief into a system where projects, value and progression can be seen.</p><dl><div><dt>20 years</dt><dd>Future-proofing talent</dd></div><div><dt>80,000+</dt><dd>Professionals transformed</dd></div></dl></div></div></section>
    <section class="section about-story" aria-labelledby="about-story-title"><div class="shell about-story__grid"><div><p class="kicker">Our answer to AI</p><h2 id="about-story-title">Build the innovators already inside the organisation.</h2></div><div><p>The AI × Talent Accelerator gives managers a six-month pathway to individually propose, build and deploy an AI-enabled, KPI-aligned innovation project with measurable business impact.</p><p>We are practitioners first. Our team has worked inside complex organisations across Malaysia, Singapore, Cambodia, the Philippines and beyond. The standard is the same: real problems, real evidence and real movement.</p></div></div></section>
    <section class="trust-section trust-section--about"><div class="shell"><p class="trust-title">Organisations that have built with Leadapreneur</p>${logoStrip()}</div></section>
    <section class="section team-section" aria-labelledby="team-title"><div class="shell">${sectionHeading('Our team', '<span id="team-title">A tight team built around the work.</span>', 'Coaches, designers, operators and business-development professionals across Southeast Asia.')}<div class="team-grid">${team.map(([name, role, image]) => `<article class="team-card reveal"><img src="${image}" alt="${name}" width="500" height="500" loading="lazy"><div><h3>${name}</h3><p>${role}</p></div></article>`).join('')}</div></div></section>
    ${finalCta()}`;
}
